---
driver:
  name: vagrant
  network:
    - ["public_network", bridge: "wlp3s0"]

provisioner:
  name: ansible_playbook
  playbook: test/test.yml
  ansible_diff: true
  hosts: localhost
  require_ruby_for_busser: false

platforms:
  - name: centos-7.1
    driver_config:
      box: chef/centos-7.1
    provisioner:
      ansible_yum_repo: "http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"

  - name: centos-6.7
    driver_config:
      box: chef/centos-6.7
    provisioner:
      ansible_yum_repo: "http://mirror.logol.ru/epel/6/x86_64/epel-release-6-8.noarch.rpm"

suites:
  - name: default-centos
    provisioner:
      attributes:
        extra_vars:

