---
  - name: 1.6.1 Restrict core dumps (Scored) - via pam
    lineinfile: >
      dest=/etc/security/limits.conf
      line="* hard core 0"
      insertafter=EOF
    tags:
      - scored
      - section1.6
      - section1.6.1

  - name: 1.6.1 Restrict core dumps (Scored) - via sysctl
    sysctl: >
      name=fs.suid_dumpable
      value=0
      state=present
      ignoreerrors=yes
    tags:
      - scored
      - section1.6
      - section1.6.1

  - name: 1.6.2 Configure ExecShield (Scored)
    sysctl: >
      name=kernel.exec-shield
      value=1
      state=present
      ignoreerrors=yes
    tags:
      - scored
      - section1.6
      - section1.6.2
    when: ansible_distribution_major_version == '6'

  - name: 1.6.3 Enable Randomized Virtual Memory Region Placement (Scored)
    sysctl: >
      name=kernel.randomize_va_space
      value=2
      state=present
      ignoreerrors=yes
    tags:
      - scored
      - section1.6
      - section1.6.3

