---
  - name: 5.1.1 Install the rsyslog package (Scored)
    yum: >
      name=rsyslog
      state=present
    tags:
      - scored
      - section5.1
      - section5.1.1

  - name: 5.1.2 Activate the rsyslog Service (Scored)
    service: >
      name=rsyslog
      enabled=yes
      state=started
    tags:
      - scored
      - section5.1
      - section5.1.2

  - name: 5.1.3 Configure /etc/rsyslog.conf auhth.(Not Scored)
    lineinfile:
      dest=/etc/rsyslog.conf
      regexp=^auth.
      line="auth.*,user.* /var/log/messages"
    notify:
      - Reload rsyslog
    tags:
      - notscored
      - section5.1
      - section5.1.3

  - name: 5.1.3 Configure /etc/rsyslog.conf daemon (Not Scored)
    lineinfile:
      dest=/etc/rsyslog.conf
      regexp=^daemon.
      line="daemon.* /var/log/daemon.log"
    notify:
      - Reload rsyslog
    tags:
      - notscored
      - section5.1
      - section5.1.3

  - name: 5.1.3 Configure /etc/rsyslog.conf kern (Not Scored)
    lineinfile:
      dest=/etc/rsyslog.conf
      regexp=^kern.
      line="kern.* /var/log/kern.log"
    notify:
      - Reload rsyslog
    tags:
      - notscored
      - section5.1
      - section5.1.3

  - name: 5.1.3 Configure /etc/rsyslog.conf syslog (Not Scored)
    lineinfile:
      dest=/etc/rsyslog.conf
      regexp=^syslog.
      line="syslog.* /var/log/syslog"
    notify:
      - Reload rsyslog
    tags:
      - notscored
      - section5.1
      - section5.1.3

  - name: 5.1.3 Configure /etc/rsyslog.conf lpr,news,uucp,local* (Not Scored)
    lineinfile:
      dest=/etc/rsyslog.conf
      regexp=^lpr.
      line="lpr,news,uucp,local0,local1,local2,local3,local4,local5,local6.* /var/log/unused.log"
    notify:
      - Reload rsyslog
    tags:
      - notscored
      - section5.1
      - section5.1.3

  - name: 5.1.4 Create and Set Permissions on rsyslog Log Files (Scored)
    file: >
      path=/var/log/{{ item }}
      state=touch
      owner=root
      group=wheel
      mode=0640
    with_items:
        - messages
        - kern.log
        - daemon.log
        - syslog
        - unused.log
    tags:
      - scored
      - section5.1
      - section5.1.4

  - name: 5.1.5 Configure rsyslog to Send Logs to a Remote Log Host (Scored)
    lineinfile: >
      state=present
      dest=/etc/rsyslog.conf
      regexp="^\*\.\*"
      line="*.* @@{{ rsyslog_dest }}"
    notify:
      - Reload rsyslog
    when: rsyslog_dest is defined
    tags:
      - scored
      - section5.1
      - section5.1.5

  - name: 5.1.6 Accept Remote rsyslog Messages Only on Designated Log Hosts (Not Scored)
    lineinfile: >
      state=present
      line="$ModLoad imtcp.so"
    notify:
      - Reload rsyslog
    when: rsyslog_host
    tags:
      - notscored
      - section5.1
      - section5.1.6

  - name: 5.1.6 Accept Remote rsyslog Messages Only on Designated Log Hosts (Not Scored)
    lineinfile: >
      state=present
      line="$InputTCPServerRun 514"
    notify:
      - Reload rsyslog
    when: rsyslog_host
    tags:
      - notscored
      - section5.1
      - section5.1.6

  - name: 5.2.1.1 Configure Audit Log Storage Size (Not Scored)
    lineinfile: >
      state=present
      dest=/etc/audit/auditd.conf
      regexp="^max_log_file ="
      line="max_log_file = {{ max_log_file }}"
    notify: Reload auditd Rules
    tags:
      - notscored
      - section5.2
      - section5.2.1
      - section5.2.1.1

  - name: 5.2.1.2 Disable System on Audit Log Full (Not Scored)
    lineinfile: >
      state=present
      dest=/etc/audit/auditd.conf
      regexp="^space_left_action ="
      line="space_left_action = {{ space_left_action }}"
    notify: Reload auditd Rules
    tags:
      - notscored
      - section5.2
      - section5.2.1
      - section5.2.1.2

  - name: 5.2.1.2 Disable System on Audit Log Full (Not Scored)
    lineinfile: >
      state=present
      dest=/etc/audit/auditd.conf
      regexp="^action_mail_acct ="
      line="action_mail_acct = {{ action_mail_acct }}"
    notify: Reload auditd Rules
    tags:
      - notscored
      - section5.2
      - section5.2.1
      - section5.2.1.2

  - name: 5.2.1.2 Disable System on Audit Log Full (Not Scored)
    lineinfile: >
      state=present
      dest=/etc/audit/auditd.conf
      regexp="^admin_space_left_action ="
      line="admin_space_left_action = {{ admin_space_left_action }}"
    notify: Reload auditd Rules
    tags:
      - notscored
      - section5.2
      - section5.2.1
      - section5.2.1.2

  - name: 5.2.1.3 Keep All Auditing Information (Scored)
    lineinfile: >
      state=present
      dest=/etc/audit/auditd.conf
      regexp="^max_log_file_action ="
      line="max_log_file_action = {{ max_log_file_action }}"
    notify: Reload auditd Rules
    tags:
      - scored
      - section5.2
      - section5.2.1
      - section5.2.1.3

  - name: 5.2.2 Enable auditd Service (Scored)
    service: >
      name=auditd
      enabled=yes
      state=running
    tags:
      - scored
      - section5.2
      - section5.2.2

  - name: 5.2.3 Enable Auditing for Processes That Start Prior to auditd (Scored)
    lineinfile: >
      state=present
      dest=/etc/grub.conf
      backrefs=yes
      regexp="(^\s*kernel.*)$(?<!audit=1)"
      line="\1 audit=1"
    tags:
      - scored
      - section5.2
      - section5.2.3
    when: ansible_distribution_major_version == '6'

  - name: Make sure grub2 tools are installed
    yum: name=grub2-tools state=present
    tags:
      - scored
      - section5.2
      - section5.2.3
    when: ansible_distribution_major_version == '7'

# This will add an extra line if someone can make better regexp i would be happy
  - name: 5.2.3 Enable Auditing for Processes That Start Prior to auditd (Scored)
    lineinfile:
      state: present
      dest: /etc/default/grub
      line: 'GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX audit=1"'
    tags:
      - scored
      - section5.2
      - section5.2.3
    when: ansible_distribution_major_version == '7'

  - name: Run grub2 config after mods in
    command: grub2-mkconfig -o /boot/grub2/grub.cfg
    tags:
      - scored
      - section5.2
      - section5.2.3
    when: ansible_distribution_major_version == '7'

  - name: 5.2.4 - 5.2.18 Configure auditd Rules (Scored)
    copy: >
      src=etc/audit/audit.rules
      dest=/etc/audit/audit.rules
    notify: Reload auditd Rules
    tags:
      - scored
      - section5.2
      - section5.2.4
      - section5.2.5
      - section5.2.6
      - section5.2.7
      - section5.2.8
      - section5.2.9
      - section5.2.10
      - section5.2.11
      - section5.2.12
      - section5.2.13
      - section5.2.14
      - section5.2.15
      - section5.2.16
      - section5.2.17
      - section5.2.18

  - name: 5.3 Configure logrotate (Not Scored)
    copy: >
      src=etc/logrotate.d/syslog
      dest=/etc/logrotate.d/syslog
    tags:
      - notscored
      - section5.3
