---
- name: 1.5.1 Set User/Group Owner on /etc/grub.conf (Scored)
  file:
    path=/boot/grub/grub.conf
    owner=root
    group=root
    mode=0600
  tags:
    - scored
    - section1.5
    - section1.5.1
  when: ansible_distribution_major_version == '6'


- name: 1.5.1 Set User/Group Owner on /etc/grub.conf (Scored)
  file:
    path=/boot/grub2/grub.cfg
    owner=root
    group=root
  tags:
    - scored
    - section1.5
    - section1.5.1
  when: ansible_distribution_major_version == '7'

- name: 1.5.2 Set Permissions on /boot/grub/grub.conf (Scored)
  file:
    path=/boot/grub/grub.conf
    mode=0400
  tags:
    - scored
    - section1.5
    - section1.5.2
  when: ansible_distribution_major_version == '6'

- name: 1.5.2 Set Permissions on /boot/grub2/grub.cfg (Scored)
  file:
    path=/boot/grub2/grub.cfg
    mode=0400
  when: ansible_distribution_major_version == '7'
  tags:
    - scored
    - section1.5
    - section1.5.2


- name: 1.5.3 Set boot loader password (Scored)
  debug: msg="*** Too destructive for production systems. Evaluate for your environment first."
  tags:
    - scored
    - section1.5
    - section1.5.3

- name: 1.5.4 Require authentication for single-user mode (Scored)
  debug: msg="*** Too destructive for production systems. Evaluate for your environment first."
  tags:
    - scored
    - section1.5
    - section1.5.4

- name: 1.5.5 Disable Interactive Boot (Scored)
  lineinfile: >
    dest=/etc/sysconfig/init
    regexp=^PROMPT=
    line=PROMPT=no
  tags:
    - scored
    - section1.5
    - section1.5.5

