---
  - name: 5.1.1 Install the rsyslog package (Scored)
    yum: >
      name=rsyslog
      state=present
    tags:
      - scored
      - section5.1
      - section5.1.1

  - name: 5.1.2 Activate the rsyslog Service (Scored)
    service: >
      name=rsyslog
      enabled=yes
      state=started
    tags:
      - scored
      - section5.1
      - section5.1.2

  - name: 5.1.3 Configure /etc/rsyslog.conf auhth.(Not Scored)
    lineinfile:
      dest=/etc/rsyslog.conf
      regexp=^auth.
      line="auth.*,user.* /var/log/messages"
    notify:
      - Reload rsyslog
    tags:
      - notscored
      - section5.1
      - section5.1.3

  - name: 5.1.3 Configure /etc/rsyslog.conf daemon (Not Scored)
    lineinfile:
      dest=/etc/rsyslog.conf
      regexp=^daemon.
      line="daemon.* /var/log/daemon.log"
    notify:
      - Reload rsyslog
    tags:
      - notscored
      - section5.1
      - section5.1.3

  - name: 5.1.3 Configure /etc/rsyslog.conf kern (Not Scored)
    lineinfile:
      dest=/etc/rsyslog.conf
      regexp=^kern.
      line="kern.* /var/log/kern.log"
    notify:
      - Reload rsyslog
    tags:
      - notscored
      - section5.1
      - section5.1.3

  - name: 5.1.3 Configure /etc/rsyslog.conf syslog (Not Scored)
    lineinfile:
      dest=/etc/rsyslog.conf
      regexp=^syslog.
      line="syslog.* /var/log/syslog"
    notify:
      - Reload rsyslog
    tags:
      - notscored
      - section5.1
      - section5.1.3

  - name: 5.1.3 Configure /etc/rsyslog.conf lpr,news,uucp,local* (Not Scored)
    lineinfile:
      dest=/etc/rsyslog.conf
      regexp=^lpr.
      line="lpr,news,uucp,local0,local1,local2,local3,local4,local5,local6.* /var/log/unused.log"
    notify:
      - Reload rsyslog
    tags:
      - notscored
      - section5.1
      - section5.1.3

  - name: 5.1.4 Create and Set Permissions on rsyslog Log Files (Scored)
    file: >
      path=/var/log/{{ item }}
      state=touch
      owner=root
      group=wheel
      mode=0640
    with_items:
        - messages
        - kern.log
        - daemon.log
        - syslog
        - unused.log
    tags:
      - scored
      - section5.1
      - section5.1.4

  - name: 5.1.5 Configure rsyslog to Send Logs to a Remote Log Host (Scored)
    lineinfile: >
      state=present
      dest=/etc/rsyslog.conf
      regexp="^\*\.\*"
      line="*.* @@{{ rsyslog_dest }}"
    when: rsyslog_dest is defined
    tags:
      - scored
      - section5.1
      - section5.1.5

  - name: 5.1.6 Accept Remote rsyslog Messages Only on Designated Log Hosts (Not Scored)
    lineinfile: >
      state=present
      line="$ModLoad imtcp.so"
    when: rsyslog_host
    tags:
      - notscored
      - section5.1
      - section5.1.6

  - name: 5.1.6 Accept Remote rsyslog Messages Only on Designated Log Hosts (Not Scored)
    lineinfile: >
      state=present
      line="$InputTCPServerRun 514"
    when: rsyslog_host
    tags:
      - notscored
      - section5.1
      - section5.1.6

  - name: 5.3 Configure logrotate (Not Scored)
    copy: >
      src=etc/logrotate.d/syslog
      dest=/etc/logrotate.d/syslog
    tags:
      - notscored
      - section5.3
