---
- name: 1.1.1 Create Separate Partition for /tmp (Scored)
  debug: msg="*** Manually create Separate Partition for /tmp."
  tags:
    - scored
    - section1.1
    - section1.1.1

- name: 1.1.2 - 1.1.4 Set nodev,nosuid,noexec option for /tmp Partition (Scored)
  mount: >
    name="/tmp"
    src={{ item.device }}
    state=mounted
    fstype={{ item.fstype }}
    opts="nodev,nosuid,noexec"
  when: item.mount == "/tmp"
  with_items: ansible_mounts
  tags:
    - scored
    - section1.1
    - section1.1.2
    - section1.1.3
    - section1.1.4

- name: 1.1.5 Create Separate Partition for /var (Scored)
  debug: msg="*** Manually create Separate Partition for /var."
  tags:
    - scored
    - section1.1
    - section1.1.5

- name: 1.1.6 Bind Mount the /var/tmp directory to /tmp (Scored)
  mount: >
    name="/var/tmp"
    src="/tmp"
    state=mounted
    fstype="none"
    opts="bind"
  when: item.mount == "/tmp"
  with_items: ansible_mounts
  tags:
    - scored
    - section1.1
    - section1.1.6

- name: 1.1.7 Create Separate Partition for /var/log (Scored)
  debug: msg="*** Manually create Separate Partition for /var/log."
  tags:
    - scored
    - section1.1
    - section1.1.7

- name: 1.1.8 Create Separate Partition for /var/log/audit (Scored)
  debug: msg="*** Manually create Separate Partition for /var/log/audit."
  tags:
    - scored
    - section1.1
    - section1.1.8

- name: 1.1.9 Create Separate Partition for /home (Scored)
  debug: msg="*** Manually create Separate Partition for /home."
  tags:
    - scored
    - section1.1
    - section1.1.9

- name: 1.1.10 Add nodev Option to /home Partition (Scored)
  mount: >
    name="/home"
    src={{ item.device }}
    state=mounted
    fstype={{ item.fstype }}
    opts="nodev"
  when: item.mount == "/home"
  with_items: ansible_mounts
  tags:
    - scored
    - section1.1
    - section1.1.10

- name: 1.1.11 Add nodev Option to Removable Media Partitions (Not Scored)
  debug: msg="*** Not relevant."
  tags:
    - scored
    - section1.1
    - section1.1.11

- name: 1.1.12 Add noexec Option to Removable Media Partitions (Not Scored)
  debug: msg="*** Not relevant."
  tags:
    - notscored
    - section1.1
    - section1.1.12

- name: 1.1.13 Add nosuid Option to Removable Media Partitions (Not Scored)
  debug: msg="*** Not relevant."
  tags:
    - notscored
    - section1.1
    - section1.1.13

- name: 1.1.14 - 1.1.16 Add noexec Option to /dev/shm Partition (Scored)
  mount: >
    name="/dev/shm"
    src="none"
    state=mounted
    fstype="tmpfs"
    opts="nodev,nosuid,noexec"
  tags:
    - section1.1
    - section1.1.14
    - section1.1.15
    - section1.1.16
    - scored

- name: 1.1.17 Set sticky bit on all world-writeable directories (Scored)
  debug: msg="*** May be too destructive -- see notes"
  tags:
    - scored
    - section1.1
    - section1.1.17

- name: Create /etc/modprobe.d/CIS.conf with root ownership & mode
  file: path=/etc/modprobe.d/CIS.conf state=touch owner=root group=root mode=0600
  changed_when: false
  tags:
    - notscored
    - section1.1
    - section1.1.18
    - section1.1.19
    - section1.1.20
    - section1.1.21
    - section1.1.22
    - section1.1.23
    - section1.1.24

- name: 1.1.18 Disable Mounting of cramfs Filesystems (Not Scored)
  lineinfile: >
    state=present
    dest=/etc/modprobe.d/CIS.conf
    line="install cramfs /bin/true"
  tags:
    - notscored
    - section1.1
    - section1.1.18

- name: 1.1.19 Disable Mounting of freevxfs Filesystems (Not Scored)
  lineinfile: >
    state=present
    dest=/etc/modprobe.d/CIS.conf
    line="install freevxfs /bin/true"
  tags:
    - notscored
    - section1.1
    - section1.1.19

- name: 1.1.20 Disable Mounting of jffs2 Filesystems (Not Scored)
  lineinfile: >
    state=present
    dest=/etc/modprobe.d/CIS.conf
    line="install jffs2 /bin/true"
  tags:
    - notscored
    - section1.1
    - section1.1.20

- name: 1.1.21 Disable Mounting of hfs Filesystems (Not Scored)
  lineinfile: >
    state=present
    dest=/etc/modprobe.d/CIS.conf
    line="install hfs /bin/true"
  tags:
    - notscored
    - section1.1
    - section1.1.21

- name: 1.1.22 Disable Mounting of hfsplus Filesystems (Not Scored)
  lineinfile: >
    state=present
    dest=/etc/modprobe.d/CIS.conf
    line="install hfsplus /bin/true"
  tags:
    - notscored
    - section1.1
    - section1.1.22

- name: 1.1.23 Disable Mounting of squashfs Filesystems (Not Scored)
  lineinfile: >
    state=present
    dest=/etc/modprobe.d/CIS.conf
    line="install squashfs /bin/true"
  tags:
    - notscored
    - section1.1
    - section1.1.23

- name: 1.1.24 Disable Mounting of udf Filesystems (Not Scored)
  lineinfile: >
    state=present
    dest=/etc/modprobe.d/CIS.conf
    line="install udf /bin/true"
  tags:
    - notscored
    - section1.1
    - section1.1.24
