---
- name: 1.2.1 Configure Connection to the RHN RPM repositories (Not Scored)
  command: yum check-update
  register: result
  failed_when: "result.rc == 1"
  when: ansible_distribution == "RedHat"
  tags:
    - notscored
    - section1.2
    - section1.2.1

- name: 1.2.2 Verify Red Hat GPG key is installed (Scored)
  command: gpg --quiet --with-fingerprint /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
  when: ansible_distribution == "RedHat"
  tags:
    - scored
    - section1.2
    - section1.2.2

- name: 1.2.2 Verify CentOS GPG key is installed (Scored)
  command: gpg --quiet --with-fingerprint /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-{{ ansible_distribution_major_version }}
  when: ansible_distribution == "CentOS"
  tags:
      - scored
      - section1.2
      - section1.2.2

- name: 1.2.3 Verify that gpgcheck is Globally Activated (Scored)
  lineinfile: >
    state=present
    dest=/etc/yum.conf
    regexp=^gpgcheck=
    line=gpgcheck=1
  tags:
    - scored
    - section1.2
    - section1.2.3

- name: 1.2.4 Disable the rhnsd Daemon (Not Scored)
  debug: msg='*** Check if you want to disable rhnsd or not with => systemctl is-enabled rhnsd'
  tags:
    - notscored
    - section1.2
    - section1.2.4

- name: 1.2.4 Check to see if rhnsd daemon is installed (Not Scored)
  stat: path=/etc/init.d/rhnsd
  register: rhnsd_service
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == '6'
  tags:
    - notscored
    - section1.2
    - section1.2.4

- name: 1.2.5 Obtain software package updates with yum (Not Scored)
  debug: msg="*** Check manually with => yum check-update"
  tags:
    - notscored
    - section1.2
    - section1.2.5

- name: 1.2.6 Verify package integrity using RPM (Not Scored)
  debug: msg="*** Check via cron/AIDE/manually"
  tags:
    - notscored
    - section1.2
    - section1.2.6
